defmodule Autoforge.Repo.Migrations.AddConfigToTools do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tools) do
      add :config, :map
    end
  end

  def down do
    alter table(:tools) do
      remove :config
    end
  end
end
