defmodule Autoforge.Repo.Migrations.AddDefaultComputeToServiceAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:google_service_account_configs) do
      add :default_compute, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:google_service_account_configs) do
      remove :default_compute
    end
  end
end
