defmodule Autoforge.Repo.Migrations.AddUserSshKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :ssh_public_key, :text
      add :encrypted_ssh_private_key, :binary
    end
  end

  def down do
    alter table(:users) do
      remove :encrypted_ssh_private_key
      remove :ssh_public_key
    end
  end
end
