defmodule Autoforge.Repo.Migrations.AddProjectTemplateUserGroups do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:project_template_user_groups, primary_key: false) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_template_id,
          references(:project_templates,
            column: :id,
            name: "project_template_user_groups_project_template_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false

      add :user_group_id,
          references(:user_groups,
            column: :id,
            name: "project_template_user_groups_user_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false
    end
  end

  def down do
    drop constraint(
           :project_template_user_groups,
           "project_template_user_groups_project_template_id_fkey"
         )

    drop constraint(
           :project_template_user_groups,
           "project_template_user_groups_user_group_id_fkey"
         )

    drop table(:project_template_user_groups)
  end
end
