defmodule Autoforge.Repo.Migrations.AddCodeServerPort do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :code_server_port, :bigint
    end
  end

  def down do
    alter table(:projects) do
      remove :code_server_port
    end
  end
end
