defmodule Autoforge.Repo.Migrations.AddLlmProviderKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:llm_provider_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "llm_provider_keys_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :encrypted_value, :binary, null: false
    end

    create unique_index(:llm_provider_keys, [:user_id, :provider],
             name: "llm_provider_keys_unique_provider_per_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:llm_provider_keys, [:user_id, :provider],
                     name: "llm_provider_keys_unique_provider_per_user_index"
                   )

    drop constraint(:llm_provider_keys, "llm_provider_keys_user_id_fkey")

    drop table(:llm_provider_keys)
  end
end
