defmodule Autoforge.Repo.Migrations.AddProjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :container_id, :text
      add :db_container_id, :text
      add :network_id, :text
      add :db_name, :text, null: false
      add :error_message, :text
      add :last_activity_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "creating"
      add :project_template_id, :uuid, null: false
      add :user_id, :uuid, null: false
      add :encrypted_db_password, :binary, null: false
    end

    create table(:project_user_groups, primary_key: false) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "project_user_groups_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false

      add :user_group_id,
          references(:user_groups,
            column: :id,
            name: "project_user_groups_user_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false
    end

    create table(:project_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:projects) do
      modify :project_template_id,
             references(:project_templates,
               column: :id,
               name: "projects_project_template_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "projects_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:project_templates) do
      add :name, :text, null: false
      add :description, :text
      add :base_image, :text, null: false
      add :bootstrap_script, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:project_templates, [:name], name: "project_templates_unique_name_index")

    create table(:project_template_files, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :content, :text
      add :is_directory, :boolean, null: false, default: false
      add :sort_order, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_template_id,
          references(:project_templates,
            column: :id,
            name: "project_template_files_project_template_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :parent_id,
          references(:project_template_files,
            column: :id,
            name: "project_template_files_parent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:project_template_files, "project_template_files_project_template_id_fkey")

    drop constraint(:project_template_files, "project_template_files_parent_id_fkey")

    drop table(:project_template_files)

    drop_if_exists unique_index(:project_templates, [:name],
                     name: "project_templates_unique_name_index"
                   )

    alter table(:project_templates) do
      remove :updated_at
      remove :inserted_at
      remove :bootstrap_script
      remove :base_image
      remove :description
      remove :name
    end

    drop constraint(:projects, "projects_project_template_id_fkey")

    drop constraint(:projects, "projects_user_id_fkey")

    alter table(:projects) do
      modify :user_id, :uuid
      modify :project_template_id, :uuid
    end

    drop table(:project_templates)

    drop constraint(:project_user_groups, "project_user_groups_project_id_fkey")

    drop constraint(:project_user_groups, "project_user_groups_user_group_id_fkey")

    drop table(:project_user_groups)

    drop table(:projects)
  end
end
