defmodule Autoforge.Repo.Migrations.AddTools do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_group_tools, primary_key: false) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_group_id,
          references(:user_groups,
            column: :id,
            name: "user_group_tools_user_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false

      add :tool_id, :uuid, null: false, primary_key: true
    end

    create table(:tools, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:user_group_tools) do
      modify :tool_id,
             references(:tools,
               column: :id,
               name: "user_group_tools_tool_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:tools) do
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tools, [:name], name: "tools_unique_name_index")

    execute """
    INSERT INTO tools (id, name, description, inserted_at, updated_at) VALUES
      (gen_random_uuid(), 'get_time', 'Get the current UTC time in ISO8601 format.', now(), now()),
      (gen_random_uuid(), 'get_url', 'Fetch the contents of a URL via HTTP GET.', now(), now())
    ON CONFLICT (name) DO NOTHING
    """

    create table(:bot_tools, primary_key: false) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bot_id,
          references(:bots,
            column: :id,
            name: "bot_tools_bot_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false

      add :tool_id,
          references(:tools,
            column: :id,
            name: "bot_tools_tool_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false
    end
  end

  def down do
    drop constraint(:bot_tools, "bot_tools_bot_id_fkey")

    drop constraint(:bot_tools, "bot_tools_tool_id_fkey")

    drop table(:bot_tools)

    drop_if_exists unique_index(:tools, [:name], name: "tools_unique_name_index")

    alter table(:tools) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop constraint(:user_group_tools, "user_group_tools_tool_id_fkey")

    alter table(:user_group_tools) do
      modify :tool_id, :uuid
    end

    drop table(:tools)

    drop constraint(:user_group_tools, "user_group_tools_user_group_id_fkey")

    drop table(:user_group_tools)
  end
end
