defmodule Autoforge.Repo.Migrations.AddVmManagement do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:vm_management_ops, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :operation_type, :text, null: false
      add :result, :map
      add :error_message, :text
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime
      add :triggered_by, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "pending"

      add :vm_instance_id,
          references(:vm_instances,
            column: :id,
            name: "vm_management_ops_vm_instance_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    alter table(:vm_instances) do
      add :encrypted_ssh_private_key, :binary
    end

    create table(:vm_management_ops_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "vm_management_ops_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:vm_management_ops_versions, "vm_management_ops_versions_user_id_fkey")

    drop table(:vm_management_ops_versions)

    alter table(:vm_instances) do
      remove :encrypted_ssh_private_key
    end

    drop constraint(:vm_management_ops, "vm_management_ops_vm_instance_id_fkey")

    drop table(:vm_management_ops)
  end
end
