defmodule Autoforge.Repo.Migrations.AddLabelToGoogleServiceAccountConfigs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:google_service_account_configs) do
      add :label, :text, null: true
    end

    execute "UPDATE google_service_account_configs SET label = project_id WHERE label IS NULL"

    alter table(:google_service_account_configs) do
      modify :label, :text, null: false
    end
  end

  def down do
    alter table(:google_service_account_configs) do
      remove :label
    end
  end
end
