defmodule Autoforge.Repo.Migrations.AddTailscaleConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tailscale_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :oauth_client_id, :text, null: false
      add :tailnet_name, :text, null: false
      add :tag, :text, null: false, default: "tag:autoforge"
      add :enabled, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :encrypted_oauth_client_secret, :binary, null: false
    end

    alter table(:projects) do
      add :tailscale_container_id, :text
      add :tailscale_hostname, :text
    end
  end

  def down do
    alter table(:projects) do
      remove :tailscale_hostname
      remove :tailscale_container_id
    end

    drop table(:tailscale_configs)
  end
end
