defmodule Autoforge.Repo.Migrations.UpdateVmTemplateDiskSizeDefault do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:vm_templates) do
      modify :disk_size_gb, :bigint, default: 50
    end
  end

  def down do
    alter table(:vm_templates) do
      modify :disk_size_gb, :bigint, default: 20
    end
  end
end
