defmodule Autoforge.Repo.Migrations.AddVmTemplatesAndInstances do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:vm_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :machine_type, :text, null: false, default: "e2-medium"

      add :os_image, :text,
        null: false,
        default: "projects/debian-cloud/global/images/family/debian-12"

      add :disk_size_gb, :bigint, null: false, default: 20
      add :disk_type, :text, null: false, default: "pd-standard"
      add :region, :text, null: false, default: "us-central1"
      add :zone, :text, null: false, default: "us-central1-a"
      add :network_tags, {:array, :text}, null: false, default: []
      add :labels, :map, null: false, default: %{}
      add :startup_script, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:vm_templates, [:name], name: "vm_templates_unique_name_index")

    create table(:vm_instances, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :gce_instance_name, :text
      add :gce_zone, :text
      add :gce_project_id, :text
      add :external_ip, :text
      add :tailscale_ip, :text
      add :tailscale_hostname, :text
      add :error_message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "creating"

      add :vm_template_id,
          references(:vm_templates,
            column: :id,
            name: "vm_instances_vm_template_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing
          ),
          null: false
    end
  end

  def down do
    drop constraint(:vm_instances, "vm_instances_vm_template_id_fkey")

    drop table(:vm_instances)

    drop_if_exists unique_index(:vm_templates, [:name], name: "vm_templates_unique_name_index")

    drop table(:vm_templates)
  end
end
