defmodule Autoforge.Repo.Migrations.AddUserGroups do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:user_groups, [:name], name: "user_groups_unique_name_index")

    create table(:user_group_memberships, primary_key: false) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_group_id,
          references(:user_groups,
            column: :id,
            name: "user_group_memberships_user_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "user_group_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false
    end
  end

  def down do
    drop constraint(:user_group_memberships, "user_group_memberships_user_group_id_fkey")

    drop constraint(:user_group_memberships, "user_group_memberships_user_id_fkey")

    drop table(:user_group_memberships)

    drop_if_exists unique_index(:user_groups, [:name], name: "user_groups_unique_name_index")

    drop table(:user_groups)
  end
end
