defmodule Autoforge.Repo.Migrations.AddDeployments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:deployments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :container_id, :text
      add :db_container_id, :text
      add :network_id, :text
      add :container_port, :bigint, null: false, default: 4000
      add :external_port, :bigint
      add :image, :text, null: false
      add :db_name, :text, null: false
      add :domain, :text
      add :error_message, :text
      add :deployed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "pending"

      add :project_id,
          references(:projects,
            column: :id,
            name: "deployments_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing
          ),
          null: false

      add :vm_instance_id,
          references(:vm_instances,
            column: :id,
            name: "deployments_vm_instance_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing
          ),
          null: false

      add :encrypted_db_password, :binary, null: false
    end

    create table(:deployment_env_vars, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :deployment_id,
          references(:deployments,
            column: :id,
            name: "deployment_env_vars_deployment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :encrypted_value, :binary, null: false
    end

    create unique_index(:deployment_env_vars, [:deployment_id, :key],
             name: "deployment_env_vars_unique_key_per_deployment_index"
           )
  end

  def down do
    drop_if_exists unique_index(:deployment_env_vars, [:deployment_id, :key],
                     name: "deployment_env_vars_unique_key_per_deployment_index"
                   )

    drop constraint(:deployment_env_vars, "deployment_env_vars_deployment_id_fkey")

    drop table(:deployment_env_vars)

    drop constraint(:deployments, "deployments_project_id_fkey")

    drop constraint(:deployments, "deployments_vm_instance_id_fkey")

    drop table(:deployments)
  end
end
