defmodule Autoforge.Repo.Migrations.AddDevServerScriptToTemplates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:project_templates) do
      add :dev_server_script, :text
    end
  end

  def down do
    alter table(:project_templates) do
      remove :dev_server_script
    end
  end
end
