defmodule Autoforge.Repo.Migrations.MakeDeploymentImageNullable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:deployments) do
      modify :image, :text, null: true
    end
  end

  def down do
    alter table(:deployments) do
      modify :image, :text, null: false
    end
  end
end
