defmodule Autoforge.Repo.Migrations.AddGithubFieldsToProjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :github_repo_owner, :text
      add :github_repo_name, :text
    end
  end

  def down do
    alter table(:projects) do
      remove :github_repo_name
      remove :github_repo_owner
    end
  end
end
