defmodule Autoforge.Repo.Migrations.AddUserProfileFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :name, :text
      add :timezone, :text, null: false, default: "America/New_York"
    end
  end

  def down do
    alter table(:users) do
      remove :timezone
      remove :name
    end
  end
end
