defmodule Autoforge.Repo.Migrations.AddDbImageToTemplates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:project_templates) do
      add :db_image, :text, null: false, default: "postgres:18-alpine"
    end
  end

  def down do
    alter table(:project_templates) do
      remove :db_image
    end
  end
end
