defmodule Autoforge.Repo.Migrations.AddGcsStorageConfigs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:gcs_storage_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :label, :text, null: false
      add :bucket_name, :text, null: false
      add :path_prefix, :text
      add :enabled, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :service_account_config_id,
          references(:google_service_account_configs,
            column: :id,
            name: "gcs_storage_configs_service_account_config_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:gcs_storage_configs, "gcs_storage_configs_service_account_config_id_fkey")

    drop table(:gcs_storage_configs)
  end
end
