defmodule Autoforge.Repo.Migrations.AddConversationCascadeDeletes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:messages, "messages_conversation_id_fkey")

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:conversation_participants, "conversation_participants_conversation_id_fkey")

    alter table(:conversation_participants) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "conversation_participants_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:conversation_bots, "conversation_bots_conversation_id_fkey")

    alter table(:conversation_bots) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "conversation_bots_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:conversation_bots, "conversation_bots_conversation_id_fkey")

    alter table(:conversation_bots) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "conversation_bots_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:conversation_participants, "conversation_participants_conversation_id_fkey")

    alter table(:conversation_participants) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "conversation_participants_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:messages, "messages_conversation_id_fkey")

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
