defmodule Autoforge.Repo.Migrations.AddGithubTokenToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :encrypted_github_token, :binary
    end
  end

  def down do
    alter table(:users) do
      remove :encrypted_github_token
    end
  end
end
