defmodule Autoforge.Repo.Migrations.AddProjectEnvVars do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:project_env_vars, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "project_env_vars_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :encrypted_value, :binary, null: false
    end

    create unique_index(:project_env_vars, [:project_id, :key],
             name: "project_env_vars_unique_key_per_project_index"
           )
  end

  def down do
    drop_if_exists unique_index(:project_env_vars, [:project_id, :key],
                     name: "project_env_vars_unique_key_per_project_index"
                   )

    drop constraint(:project_env_vars, "project_env_vars_project_id_fkey")

    drop table(:project_env_vars)
  end
end
