defmodule Autoforge.Repo.Migrations.ReplaceBotUserWithBotUserGroups do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bots) do
      remove :user_id
    end

    drop_if_exists unique_index(:bots, [:user_id, :name], name: "bots_unique_name_per_user_index")

    create unique_index(:bots, [:name], name: "bots_unique_name_index")

    create table(:bot_user_groups, primary_key: false) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bot_id,
          references(:bots,
            column: :id,
            name: "bot_user_groups_bot_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false

      add :user_group_id,
          references(:user_groups,
            column: :id,
            name: "bot_user_groups_user_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false
    end
  end

  def down do
    drop constraint(:bot_user_groups, "bot_user_groups_bot_id_fkey")

    drop constraint(:bot_user_groups, "bot_user_groups_user_group_id_fkey")

    drop table(:bot_user_groups)

    drop_if_exists unique_index(:bots, [:name], name: "bots_unique_name_index")

    create unique_index(:bots, [:user_id, :name], name: "bots_unique_name_per_user_index")

    alter table(:bots) do
      add :user_id,
          references(:users,
            column: :id,
            name: "bots_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end
end
